### ISSUE TITLE
convertRelativeUrls anwenden, um Pfade im RSS absolut zu setzen

### ISSUE THREAD

**Issue by addorange** [cliffparnitzky-archive/summarizeFeeds#11]
Ich habe leider keine passende Funktion im Code gefunden, daher folgende Stelle in generateFile($arrFeed) eingebaut:

$objItem->description = $this->convertRelativeUrls($objItem->description, $strLink);

Bei mir passt das so.

Viele Grüße,

Christian

**Comment by cliffparnitzky** [comment]
Not longer supported
